[package]
name = "piclabeler"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Marius Bär <me@mariusbaer.de>"]
license = "MIT"
description = "Annotate images with labels and arrows"
categories = ["visualization"]
